name: fantasy_manager
description: Aplicación multiplataforma Fantasy Manager desarrollada con Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado y gestión
  provider: ^6.1.1
  
  # HTTP y API
  http: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utilidades
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
