services:
  postgres:
    image: postgres:16
    container_name: kanban_postgres
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: